### PR TITLE
Feature/branch step

### PR DESCRIPTION
**Pull request by dalu93**
Adding `branch` step as per #18 
This should switch branch if it already exists, or create a new one.
The `push` step should push and create the branch remotely, if it doesn't exist.

### CODE REVIEW

**Comment by f-meloni** [comment]
Cool, thank you for the PR.
The only thing is that I think it would fail if you launch `git checkout -b` with an existing branch, then probably i would suggest to make the branchName mandatory, because using master would make it fail almost for every project.
Something like this:
https://github.com/f-meloni/Rocket/blob/master/Sources/RocketLib/Executors/ScriptExecutor.swift#L6
Everything else is great!

**Comment by f-meloni** [comment]
Also can you please update the README? :)
After with those two things i will merge this and release a new version straight away 👍

**Comment by dalu93** [comment]
Thank @f-meloni, I just added a commit addressing your points

**Comment by f-meloni** [comment]
Thanks to you @dalu93, will wait the CI and then i will merge it. 👍

**Comment by f-meloni** [comment]
Released on `0.5.0` 👍

**Pull request merged**
